In [3]:
import numpy as np
demo = np.array([[30,75,70],[80,90,20],[50,95,60]])
print(demo)
print('\n')
print(np.mean(demo))
print(np.median(demo))
print('\n')

[[30 75 70]
 [80 90 20]
 [50 95 60]]


63.333333333333336
70.0




In [4]:
import pandas as pd
import numpy as np
d={'Name':pd.Series(['Ram','Sham','Menna','Seeta','Geeta','Rakesh','Madhav']),
    'Age':pd.Series([25,26,25,23,30,29,23]),
     'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}
df=pd.DataFrame(d)
print(df.sum())

Name      RamShamMennaSeetaGeetaRakeshMadhav
Age                                      181
Rating                                 25.61
dtype: object


In [5]:
import pandas as pd
import numpy as np
md={'Name':pd.Series(['Ram','Sham','Meena','Seeta','Geeta','Rakesh','Madhav']),
     'Age':pd.Series([25,26,25,23,30,29,23]),
      'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}
df=pd.DataFrame(d)
print(df.describe())

             Age    Rating
count   7.000000  7.000000
mean   25.857143  3.658571
std     2.734262  0.698628
min    23.000000  2.560000
25%    24.000000  3.220000
50%    25.000000  3.800000
75%    27.500000  4.105000
max    30.000000  4.600000


In [6]:
import numpy as np
data=np.array([13,52,44,32,30,0,36,45])
print("Standard Deviation Of Sample is %s "%(np.std(data)))

Standard Deviation Of Sample is 16.263455967290593 


In [7]:
import pandas as pd
import scipy.stats as s
score={'Virat':[92,97,85,74,71,55,85,63,42,32,71,55],'Rohit':[89,87,67,55,47,72,76,79,44,92,99,47]}
df=pd.DataFrame(score)
print(df)
print("\n Arithmetic Mean Values")
print("Score 1 = ",s.tmean(df["Virat"].round(2)))
print("Score 2 = ",s.tmean(df["Rohit"].round(2)))

    Virat  Rohit
0      92     89
1      97     87
2      85     67
3      74     55
4      71     47
5      55     72
6      85     76
7      63     79
8      42     44
9      32     92
10     71     99
11     55     47

 Arithmetic Mean Values
Score 1 =  68.5
Score 2 =  71.16666666666667


In [9]:
import pandas as pd
from scipy.stats import iqr
import matplotlib.pyplot as plt
d={'Name':['Ravi','Veena','Meena','Rupali'],'subject':[92,97,85,74]}
df=pd.DataFrame(d)
df=pd.DataFrame(d)
df['Percentile_rank']=df.subject.rank(pct=True)
print("\nValues Of Percentile Rank In The Distribution")
print(df)
print("\nMeasures of Dispersion And Position in the Distribution")
r=max(df["subject"])-min(df["subject"])
print("\nValue of Range in the Distribution = ",r)
s=round(df["subject"].std(),3)
print("Value Of Standard Deviation in the Distribution = ",s)
v=round(df["subject"].var(),3)
print("Value of Variance in the Distribution = ",v)


Values Of Percentile Rank In The Distribution
     Name  subject  Percentile_rank
0    Ravi       92             0.75
1   Veena       97             1.00
2   Meena       85             0.50
3  Rupali       74             0.25

Measures of Dispersion And Position in the Distribution

Value of Range in the Distribution =  23
Value Of Standard Deviation in the Distribution =  9.967
Value of Variance in the Distribution =  99.333


In [2]:
import numpy as np
mydata=np.array([24,29,20,22,24,26,30,20,31,26,38,44,47])
q3,q1=np.percentile(mydata,[75,25])
iqrvalue=q3-q1
print(iqrvalue)

7.0
